{% set name = "qt5reactor" %}
{% set version = "0.6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "b375af4ac359035499c98d3bc9a77baed0617a9216121abfa9a344bdf8d9981f" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [win or py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - twisted
  run:
    - pyqt >=5
    - python
    - twisted

test:
  imports:
    - qt5reactor

about:
  home: https://github.com/sunu/qt5reactor
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Twisted Qt Integration

extra:
  recipe-maintainers:
    - mrakitin
