{% set name = "qt5reactor" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f02e45ffa891eea98cfba39dccf719dcd515fa73254bb4d53ba936f3d7836f0

build:
  number: 0
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - twisted
  run:
    - pyqt >=5
    - python
    - twisted

test:
  imports:
    - qt5reactor

about:
  home: https://github.com/sunu/qt5reactor
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Twisted Qt Integration

extra:
  recipe-maintainers:
    - mrakitin
