travis:
  secure:
    BINSTAR_TOKEN: oZfC005K336ljXJSc2BX9b6qJhJNMBBMGCrOiAmsL4gGtdtejkZ3Ch9hiQFHMqUbV8+oGfzx2P+MsAsOuB76KOdx54t8Cp2mdWR+AbbXjmYnGVXRj/9MB2yJb5Z5IiGSqum93CSSaIDELbHkBs2HFuQ78BYY059CNscyrGBfOGialqpeNgxsvoyPZ3cGz7Mh7mlk5SuzwNoV+1dx3r0Oi8ezRJWdGq4Xzd7KRjD7qiWichopqUl0IEfdgDfhsqEUA1Z6sxRYukcPXPy9VQhptmmerHLE1fxOAGDSHMVULPE0xpophX5q0SqTScIH3tgssCj0amol8K7G6UL+J0eKHXBCdFIgwKLAzxHsXW4BCAmQhiM5R+xHSNyr3LWvGXBVKhBblrpqwnKj/ltk8e2QgUeee3Tfcy4ycDlcULLDCUS+OEW97SOTDNIuMpuNOUY88fgrBBvsMMnfWzKEA/LNm2nlontmwjxzVwljKX2jf70jNtTl98KdrFGPEGDjwq8t+KwGJr8ibaizgUunG32NMgiONA/f7Rp3KLe4QxNqrzAYAY32odKQgAQenIGpEht+iWHfPsu2Jv/BEU8Rk5DKSDipqMZbHTCAy8dntFvkpgfgN1D9l+Dw5XmTMsYEWsVC91Yemc91y9JhfGzbzcJkklrMPZhhzQFtrsajFUEUfMI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
